blogEntries = [
    ["javascript.html", "JavaScript"],
    ["powershell.html", "PowerShell"],
    ["css.html", "CSS"],
    ["setup.html", "Setup"],
    ["admission.html", "Admission"]
];

noteEntries = [
    ["vocabulary.html", "Vocabulary"],
    ["academy-skill.html", "Skill"],
    ["reading-notes.html", "Reading Notes"],
    ["listening-notes.html", "Listening Notes"],
    ["speaking-notes.html", "Speaking Notes"],
    ["writing-notes.html", "Writing Notes"],
    ["performance-feedback.html", "Performance"],
    ["scoring-rubric.html", "Scoring"],
    ["example-writing1.html", "Example Integrated Writing"],
    ["example-writing2.html", "Example Independent Writing Trait"],
    ["sample-writing1.html", "Sample Integrated Writing"],
    ["sample-writing2.html", "Sample Independent Writing Comparative"],
    ["sample-speaking1.html", "Sample Speaking 1"],
    ["sample-speaking2.html", "Sample Speaking 2"],
    ["sample-speaking3.html", "Sample Speaking 3"],
    ["sample-speaking4.html", "Sample Speaking 4"],
    ["sample-speaking5.html", "Sample Speaking 5"],
    ["sample-speaking6.html", "Sample Speaking 6"],
    ["example-speaking1.html", "Example Speaking 1"],
    ["example-speaking2.html", "Example Speaking 2"],
    ["example-speaking3.html", "Example Speaking 3"],
    ["example-speaking4.html", "Example Speaking 4"],
    ["example-speaking5.html", "Example Speaking 5"],
    ["example-speaking6.html", "Example Speaking 6"],
    ["reading-practice1.html", "Reading Practice 1"],
    ["reading-practice2.html", "Reading Practice 2"],
    ["reading-practice3.html", "Reading Practice 3"],
    ["reading-practice4.html", "Reading Practice 4"],
    ["reading-practice5.html", "Reading Practice 5"],
    ["reading-practice6.html", "Reading Practice 6"],
    ["listening-practice1.html", "Listening Practice 1"],
    ["listening-practice2.html", "Listening Practice 2"],
    ["listening-practice3.html", "Listening Practice 3"],
    ["listening-practice4.html", "Listening Practice 4"],
    ["listening-practice5.html", "Listening Practice 5"],
    ["sample-reading1.html", "Sample Reading 1"],
    ["sample-reading2.html", "Sample Reading 2"],
    ["sample-reading3.html", "Sample Reading 3"],
    ["sample-reading4.html", "Sample Reading 4"],
    ["sample-reading5.html", "Sample Reading 5"],
    ["sample-listening1.html", "Sample Listening 1"],
    ["sample-listening2.html", "Sample Listening 2"],
    ["sample-listening3.html", "Sample Listening 3"],
    ["sample-listening4.html", "Sample Listening 4"]
];

phrases = [
    ["Personally", "In my opinion", "From my own viewpoint", "In my own view"],
    ["In addition", "Also", "Besides", "What's more", "Furthermore", "Moreover", "Additionally"],
    ["In conclusion", "Lastly,", "Finally", "In summary", "To sum up", "To summarize", "In brief", "To conclude", "On the whole"],
    ["As a result", "To this end", "For this reason", "Consequently", "Therefore", "Thus", "Hence", "In Consequence", "Accordingly"],
    ["In general", "For the most part", "Generally speaking", "By and large"],
    ["In contrast", "Whereas", "On the contrary", "Conversely",  "But", "Yet", "However",  "Even so", "Still", "Nonetheless", "Nevertheless",  "In spite of that", "Although", "Even though", "notwithstanding", "While"],
    ["In order to", "For the purpose of", "So that", "So as to", ]
]
